import Head from "next/head";

function Home() {
 

  return (
    <div class="whole-cont">
      <Head>
        <title>personal portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style> </style>
      </Head>
      <main>
        <section class="background-grey" >
        <section className="">
          <div className="text-center pt-10">
            <h2 className="text-4xl py-2 text-gray-700 font-bold  prose lg:prose-xl">
              Name Surname
            </h2>
            <div class="box">
              <p className=" pt-2 content-center text-1xl text-white font-bold">Professional Title</p></div>
          </div>
        </section>
        <section className="flex px-10 mb-10">
          <div class="sidebar">
            <div class="contacts" className="">
              <div className="cursor-pointer flex pt-5 pb-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
  <path fill-rule="evenodd" d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z" clip-rule="evenodd" />
</svg>
 <p class="contact-txt">612-345-678</p></div>
              <div className=" cursor-pointer flex  pb-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
  <path d="M1.5 8.67v8.58a3 3 0 003 3h15a3 3 0 003-3V8.67l-8.928 5.493a3 3 0 01-3.144 0L1.5 8.67z" />
  <path d="M22.5 6.908V6.75a3 3 0 00-3-3h-15a3 3 0 00-3 3v.158l9.714 5.978a1.5 1.5 0 001.572 0L22.5 6.908z" />
</svg>

 <p class="contact-txt">yourname@gmail.com</p></div>
              <div className=" cursor-pointer flex  pb-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
  <path fill-rule="evenodd" d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd" />
</svg>
 <p class="contact-txt">New york,NY</p></div>
              <div className="cursor-pointer flex  pb-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
  <path fill-rule="evenodd" d="M19.902 4.098a3.75 3.75 0 00-5.304 0l-4.5 4.5a3.75 3.75 0 001.035 6.037.75.75 0 01-.646 1.353 5.25 5.25 0 01-1.449-8.45l4.5-4.5a5.25 5.25 0 117.424 7.424l-1.757 1.757a.75.75 0 11-1.06-1.06l1.757-1.757a3.75 3.75 0 000-5.304zm-7.389 4.267a.75.75 0 011-.353 5.25 5.25 0 011.449 8.45l-4.5 4.5a5.25 5.25 0 11-7.424-7.424l1.757-1.757a.75.75 0 111.06 1.06l-1.757 1.757a3.75 3.75 0 105.304 5.304l4.5-4.5a3.75 3.75 0 00-1.035-6.037.75.75 0 01-.354-1z" clip-rule="evenodd" />
</svg>

<p class="contact-txt">linkedin.com/name</p></div>
            

<div class="box-new">
            </div>
            </div>
            <div class="sumarry">
            <h3 className="  text-slate-800 text-lg font-bold pt-5 uppercase">Summary</h3>
            <p className="leading-5  text-xs italic pt-2 pt-3 pb-2">
                Your summary goes here. It's the
                <span className="text-black-200 font-bold"> last stage in the resume writing 
                process </span>
                ,so pick it up in the end. Focus more on what value you can provide, instead of what you are looking for.Limit it to <span className="text-black-200 font-bold"> 2-3 lines max </span>
               
              </p>
             <div class="box-new">
            </div>
            </div>
            <div class="key-skills">
            <h3 className="  text-slate-800 text-lg font-bold pt-5 uppercase">Key skills</h3>
             <ul className="flex italic flex-col pt-3 leading-7 text-xs font-medium text-gray-500 dark:text-gray-200">
                <li>Market Research 
                </li>
                <li>Social Media Strategy
               </li>
                <li>Social Media Analytics
               </li>
                <li>Social Media Content: Creattion & curation
                </li>
                <li>Marketing Collateral 
                </li>
                <li>Keyword Research
                </li>
                <li>Search Engine optimization
                </li>
                <li>Client Servicing 
                </li>
                <li>Blog Writing 
                </li>
                <li>Digital Marketing 
                </li>
                <li>Website Content
                </li>
                <li>Proofreading 
                </li>
                <li>Content Mangement & Editing
                </li>
              </ul>
             <div class="box-new">
            </div>
            </div>
            <div class="technical-skills">
            <h3 className="  text-slate-700 text-lg font-bold pt-5 uppercase"> technical skills</h3>
            <p className="text-xs italic pt-2 pt-3 pb-2 leading-6">
              <span className="text-sm text-black-200 font-bold"> Languages : </span>
               VB6 , SQL , Web Services-C#,C,C++, java, Perl
              </p>
             <ul className="flex  italic flex-col text-xs font-medium leading-6 list-disc pl-2 text-gray-500 dark:text-gray-200">
                <li><span className="text-sm text-black-200 font-bold"> Operating  Systems  : </span>   Windows  ( XP NT 3.X-4.0 2000 2003 ) and UNIX</li>
            
                <li><span className=" text-sm text-black-200 font-bold"> Databases : </span> MS SQL Server (2008,2005,2000,7.0.6.5.6.0) , MS Acess , FoxPro , DTS , DB2</li>
              </ul>
             
          </div>
          </div>
          <div class="main-content" className="pl-10">
            <div class="box-content">
            <h3 className="text-xl font-bold pl-3 pt-2 text-slate-700 uppercase">Personal experience</h3>
            
            <div className="flex justify-between">
              <h3 className="  text-slate-700 text-base font-bold pl-3 pt-3">Official Designation</h3>
              <p className="text-sm text-slate-800 font-medium pt-3">June'23 - Sep'23</p>
            </div>
            <div className=" text-slate-700 flex justify-between"> <h6 className="text-0.5xl font-bold pl-3 pt-2">Company Name</h6>
            <p className="text-sm text-slate-800 font-medium pt-2">Location</p>
            </div>
            <p className="text-xs italic pt-3 pl-5 text-gray-500 dark:text-gray-200">
                Enter a one-line description of the Company where you were working with figures arounf revenue,geographic presence, no. of clients, etc.
              </p>
              <ul className="leading-5 text-xs text-slate-800 font-medium list-disc italic pt-2 pl-10">
                <li>Use one-liner points to present the details of your part-time/professional experience
                </li>
                <li>Bold keywords and phrases where yoy would like to draw the recruiter's attention.
                </li>
                <li>Use action verbs to start off your points, and achievement figures (ballpark/appx figures will work as well) to demostrate the extent of your contributions
               </li>
                <li>Instead of writing all your one-liner points together ,group similar points under unique subheadings.</li>
              </ul>
            </div>
            <div class="box-content">
            {/* <h3 className="text-xl font-bold pl-3 pt-5 text-slate-700 uppercase">Personal experience</h3> */}
            
            <div className="flex justify-between">
              <h3 className="  text-slate-700 text-base font-bold pl-3 pt-2">Official Designation</h3>
              <p className="text-sm text-slate-800 font-medium pt-2 ">June'23 - Sep'23</p>
            </div>
            <div className=" text-slate-700 flex justify-between"> <h6 className="text-0.5xl font-bold pl-3 pt-2">Company Name</h6>
            <p className="text-sm text-slate-800 font-medium pt-2">Location</p>
            </div>
            <p className="text-xs italic pt-3 pl-5 text-gray-500 dark:text-gray-200">
                Enter a one-line description of the Company where you were working with figures arounf revenue,geographic presence, no. of clients, etc.
              </p>
              <ul className="leading-5 text-xs text-slate-800 font-medium list-disc italic pt-2 pl-10">
                <li>Use one-liner points to present the details of your part-time/professional experience
                </li>
                <li>Bold keywords and phrases where yoy would like to draw the recruiter's attention.
                </li>
                <li>Use action verbs to start off your points, and achievement figures (ballpark/appx figures will work as well) to demostrate the extent of your contributions
               </li>
                <li>Instead of writing all your one-liner points together ,group similar points under unique subheadings.</li>
              </ul>
            </div>
            
          <div class="box-new"></div>
          <div class="box-content">
            <h3 className="text-xl font-bold pl-3 pt-5 text-slate-700 uppercase">INTERNSHIPS</h3>
            
            <div className="flex justify-between">
              <h3 className="  text-slate-700 text-base font-bold pl-3 pt-2">Official Designation</h3>
              <p className="text-sm text-slate-800 font-medium pt-2">June'23 - Sep'23</p>
            </div>
            <div className=" text-slate-700 flex justify-between"> <h6 className="text-0.5xl font-bold pl-3 pt-2">Company Name</h6>
            <p className="text-sm text-slate-800 font-medium pt-2">Location</p>
            </div>
            <p className="text-xs italic pt-3 pl-5 text-gray-500 dark:text-gray-200">
                Enter a one-line description of the Company where you were working with figures arounf revenue,geographic presence, no. of clients, etc.
              </p>
            
            </div>
            <div class="box-new"></div>
            <div class="box-content">
            <h3 className="text-xl font-bold pl-3 pt-5 text-slate-700 uppercase">EDUCATION</h3>
            
            <div className="flex justify-between">
              <h3 className="  text-slate-700 text-base font-bold pl-3 pt-2">Degree with Major</h3>
              <p className="text-sm text-slate-800 font-medium pt-2">June'23 - Sep'23</p>
            </div>
            <div className=" text-slate-700 flex justify-between"> <h6 className="text-0.5xl font-bold pl-3 pt-2">Enter the name if the educational institution</h6>
            <p className="text-sm text-slate-800 font-medium pt-2 pl-14">Enter location(with state)</p>
            </div>
            <p className="text-xs italic pt-3 pl-5 text-gray-500 dark:text-gray-200">
                Enter a one-line description of the Company where you were working with figures arounf revenue,geographic presence, no. of clients, etc.
              </p>
              <ul className="leading-5 text-xs text-slate-800 font-medium list-disc italic pt-2 pl-10 pb-5">
                <li>Enter your GPA if it's higher than 3/4
                </li>
                <li>Enter your key course modules if they're relevant to the profiles you are targeting -just the name of the coursework/modules in multiple one-line bullet points.</li>
                </ul>
            </div>
            <div class="box-new"></div>
            
          </div>
          

        </section>

        </section>
      </main>
    </div>
  );
}
export default Home;